### PR TITLE
Create Span From Factory

### PR DESCRIPTION
**Pull request by datpmwork**
Span instance should be created by EventFactory instead of explicit class

### CODE REVIEW

**Comment by arkaitzgarro** [comment]
Hey @datpmwork, thanks for your contribution. Could you update your branch with latest `master`? It fixes the issue with Composer and will allow the tests to run.

**Comment by datpmwork** [comment]
@arkaitzgarro Rebased on latest master. Let's try again

**Comment by arkaitzgarro** [comment]
> @arkaitzgarro Rebased on latest master. Let's try again

Thanks! The linting and tests are failing, can you take a look and fix them?

**Comment by datpmwork** [comment]
@arkaitzgarro Removed unused import and added one expectation in test case.

**Comment by datpmwork** [comment]
@arkaitzgarro Still failed, let me setup my local env and verify in local first 😅

**Review by arkaitzgarro — APPROVED** [review]

**Pull request merged**
