### PR TITLE
Implement ApmConfigService class

### PR DESCRIPTION
**Pull request by cykirsch**
This provides a couple core benefits:
 - puts the isAgentDisabled logic in a single location instead of repeating it
 - makes the package more extensible in that the configuration gathering can be modified apart from the service provider

This is related to https://github.com/arkaitzgarro/elastic-apm-laravel/issues/69. It's not the ideal solution but to me it seems like they are still useful improvements.

I haven't quite finished all the tests; due to our difference in timezones I wanted to get this PR up tonight in hopes of some feedback before wrapping it up tomorrow (if you are interested in it moving forward).

### CODE REVIEW

**Comment by arkaitzgarro** [comment]
Looking good, thanks! Do you think we should create a Facade to access the package configuration from the apps?

**Comment by cykirsch** [comment]
@arkaitzgarro Tough to say, most of it is available via the framework facade and helper already. Adding it now would just allow access to the "resolved" values. That is, 

- the config as formatted for the agent--I don't see the need
- the isAgentDisabled()--Potentially useful in custom collectors, but if you're making a custom collector you might as well just inject the service 🤷‍♂️ 

It'll be a quick add if you want me to, but I'd personally do without until someone asks for it.

**Comment by cykirsch** [comment]
Unfortunately I'm running into more issues in actual usage. In trying to extend, I'm still hitting the parent config because it gets called when we init the FrameworkCollector. This is an issue that would be solved by the AgentBuilder concept in https://github.com/arkaitzgarro/elastic-apm-laravel/pull/70. I'm still open to improving this and merging later but for now I think I'd consider it broken without #70.

**Comment by arkaitzgarro** [comment]
Hey @cykirsch, any update on this change?

**Comment by cykirsch** [comment]
No update. I can try to sneak in some time this week to see if it works better on the latest RC.

**Comment by cykirsch** [comment]
I don't have plans for this right now. Feel free to tag me with any questions if implementing this in some way in the future.

**Pull request closed without merging**
